CREATE OR REPLACE FUNCTION gist_tree(text)
RETURNS text
AS '$libdir/gevel'
LANGUAGE C STRICT IMMUTABLE PARALLEL SAFE;

CREATE OR REPLACE FUNCTION gist_tree(text,int4)
RETURNS text
AS '$libdir/gevel'
LANGUAGE C STRICT IMMUTABLE PARALLEL SAFE;

CREATE OR REPLACE FUNCTION gist_stat(text)
RETURNS text
AS '$libdir/gevel'
LANGUAGE C STRICT IMMUTABLE PARALLEL SAFE;

CREATE OR REPLACE FUNCTION gist_print(text)
RETURNS setof record
AS '$libdir/gevel'
LANGUAGE C STRICT IMMUTABLE PARALLEL SAFE;

CREATE OR REPLACE FUNCTION gin_stat(text)
RETURNS setof record
AS '$libdir/gevel'
LANGUAGE C STRICT IMMUTABLE PARALLEL SAFE;

CREATE OR REPLACE FUNCTION gin_stat(text, int)
RETURNS setof record
AS '$libdir/gevel'
LANGUAGE C STRICT IMMUTABLE PARALLEL SAFE;

CREATE OR REPLACE FUNCTION gin_statpage(text)
RETURNS text
AS '$libdir/gevel'
LANGUAGE C STRICT IMMUTABLE PARALLEL SAFE;

CREATE OR REPLACE FUNCTION gin_count_estimate(text, tsquery)
RETURNS bigint
AS '$libdir/gevel'
LANGUAGE C STRICT IMMUTABLE PARALLEL SAFE;

CREATE OR REPLACE FUNCTION spgist_stat(text)
RETURNS text
AS '$libdir/gevel'
LANGUAGE C STRICT IMMUTABLE PARALLEL SAFE;

CREATE OR REPLACE FUNCTION spgist_print(text)
RETURNS setof record
AS '$libdir/gevel'
LANGUAGE C STRICT IMMUTABLE PARALLEL SAFE;
